/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TryThread;

/**
 *
 * @author RIFAI
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eBarang1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eJumlah1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        eHarga1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eTotal1 = new javax.swing.JTextField();
        eCetak1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eHasil1 = new javax.swing.JTextArea();
        eBarang2 = new javax.swing.JTextField();
        eJumlah2 = new javax.swing.JTextField();
        eHarga2 = new javax.swing.JTextField();
        eTotal2 = new javax.swing.JTextField();
        eCetak2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        eHasil2 = new javax.swing.JTextArea();
        eReset1 = new javax.swing.JButton();
        eReset2 = new javax.swing.JButton();

        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Aplikasi Kasir");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Barang : ");

        eBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBarang1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah Barang : ");

        eJumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJumlah1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Satuan : ");

        eHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eHarga1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Harga : ");

        eTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTotal1ActionPerformed(evt);
            }
        });

        eCetak1.setText("Cetak");
        eCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCetak1ActionPerformed(evt);
            }
        });

        eHasil1.setColumns(20);
        eHasil1.setRows(5);
        jScrollPane1.setViewportView(eHasil1);

        eBarang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBarang2ActionPerformed(evt);
            }
        });

        eJumlah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJumlah2ActionPerformed(evt);
            }
        });

        eHarga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eHarga2ActionPerformed(evt);
            }
        });

        eTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTotal2ActionPerformed(evt);
            }
        });

        eCetak2.setText("Cetak");
        eCetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCetak2ActionPerformed(evt);
            }
        });

        eHasil2.setColumns(20);
        eHasil2.setRows(5);
        jScrollPane2.setViewportView(eHasil2);

        eReset1.setText("Reset");
        eReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eReset1ActionPerformed(evt);
            }
        });

        eReset2.setText("Reset");
        eReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eReset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eTotal1)
                                    .addComponent(eHarga1)
                                    .addComponent(eJumlah1)
                                    .addComponent(eBarang1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eCetak1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                        .addComponent(eReset1))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(eBarang2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eJumlah2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eHarga2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eTotal2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(eCetak2)
                                    .addGap(18, 18, 18)
                                    .addComponent(eReset2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eJumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCetak1)
                    .addComponent(eCetak2)
                    .addComponent(eReset1)
                    .addComponent(eReset2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCetak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eCetak1ActionPerformed

    private void eCetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCetak2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eCetak2ActionPerformed

    private void eBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBarang1ActionPerformed
        // TODO add your handling code here:
        String namaBarang1 = eBarang1.getText();
        eBarang1.setText(namaBarang1);
    }//GEN-LAST:event_eBarang1ActionPerformed

    private void eBarang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBarang2ActionPerformed
        // TODO add your handling code here:
        String namaBarang2 = eBarang2.getText();
        eBarang2.setText(namaBarang2);
    }//GEN-LAST:event_eBarang2ActionPerformed

    private void eJumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJumlah1ActionPerformed
        // TODO add your handling code here:
        String jumlahBarang1 = eJumlah1.getText();
        eJumlah1.setText(jumlahBarang1);
    }//GEN-LAST:event_eJumlah1ActionPerformed

    private void eJumlah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJumlah2ActionPerformed
        // TODO add your handling code here:
        String jumlahBarang2 = eJumlah2.getText();
        eJumlah2.setText(jumlahBarang2);
    }//GEN-LAST:event_eJumlah2ActionPerformed

    private void eHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eHarga1ActionPerformed
        // TODO add your handling code here:
        String hargaSatuan1 = eHarga1.getText();
        eHarga1.setText(hargaSatuan1);
    }//GEN-LAST:event_eHarga1ActionPerformed

    private void eHarga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eHarga2ActionPerformed
        // TODO add your handling code here:
        String hargaSatuan2 = eHarga2.getText();
        eHarga2.setText(hargaSatuan2);
    }//GEN-LAST:event_eHarga2ActionPerformed

    private void eTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTotal1ActionPerformed
        // TODO add your handling code here:
        String totalHarga1 = eTotal1.getText();
        eTotal1.setText(totalHarga1);
    }//GEN-LAST:event_eTotal1ActionPerformed

    private void eTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTotal2ActionPerformed
        // TODO add your handling code here:
        String totalHarga2 = eTotal2.getText();
        eTotal2.setText(totalHarga2);
    }//GEN-LAST:event_eTotal2ActionPerformed

    private void eReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eReset1ActionPerformed
        // TODO add your handling code here:
        eBarang1.setText("");
        eJumlah1.setText("");
        eHarga1.setText("");
        eTotal1.setText("");
    }//GEN-LAST:event_eReset1ActionPerformed

    private void eReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eReset2ActionPerformed
        // TODO add your handling code here:
        eBarang2.setText("");
        eJumlah2.setText("");
        eHarga2.setText("");
        eTotal2.setText("");
    }//GEN-LAST:event_eReset2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eBarang1;
    private javax.swing.JTextField eBarang2;
    private javax.swing.JButton eCetak1;
    private javax.swing.JButton eCetak2;
    private javax.swing.JTextField eHarga1;
    private javax.swing.JTextField eHarga2;
    private javax.swing.JTextArea eHasil1;
    private javax.swing.JTextArea eHasil2;
    private javax.swing.JTextField eJumlah1;
    private javax.swing.JTextField eJumlah2;
    private javax.swing.JButton eReset1;
    private javax.swing.JButton eReset2;
    private javax.swing.JTextField eTotal1;
    private javax.swing.JTextField eTotal2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
