/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pelaporan;

/**
 *
 * @author RIFAI
 */
public class cLogin extends javax.swing.JFrame {

    /**
     * Creates new form cLogin
     */
    public cLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ePassword1 = new javax.swing.JPasswordField();
        btnStatusLogIn = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        eNama_LogIn = new javax.swing.JTextField();
        ePassword_LogIn = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eMasyarakat = new javax.swing.JRadioButton();
        ePetugas = new javax.swing.JRadioButton();
        eSubmit_LogIn = new javax.swing.JButton();
        eReset_LogIn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        eReport_LogIn = new javax.swing.JTextArea();
        eSign_UP = new javax.swing.JButton();
        eAdmin = new javax.swing.JRadioButton();

        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setText("Form Penilaian Mahasiswa");

        jLabel13.setText("Nama Lengkap : ");

        jLabel12.setText("Log-In Aplikasi Pelaporan Pengaduan Masyarakat");

        ePassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePassword1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Log-In Aplikasi Pelaporan Pengaduan Masyarakat");

        eNama_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNama_LogInActionPerformed(evt);
            }
        });

        ePassword_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePassword_LogInActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama : ");

        jLabel10.setText("Password : ");

        jLabel11.setText("Status : ");

        btnStatusLogIn.add(eMasyarakat);
        eMasyarakat.setText("Masyarakat");

        btnStatusLogIn.add(ePetugas);
        ePetugas.setText("Petugas");

        eSubmit_LogIn.setText("Submit");
        eSubmit_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSubmit_LogInActionPerformed(evt);
            }
        });

        eReset_LogIn.setText("Reset");
        eReset_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eReset_LogInActionPerformed(evt);
            }
        });

        eReport_LogIn.setColumns(20);
        eReport_LogIn.setRows(5);
        jScrollPane2.setViewportView(eReport_LogIn);

        eSign_UP.setText("Sign-Up");
        eSign_UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSign_UPActionPerformed(evt);
            }
        });

        btnStatusLogIn.add(eAdmin);
        eAdmin.setText("Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eNama_LogIn)
                            .addComponent(ePassword_LogIn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eMasyarakat)
                                    .addComponent(eSubmit_LogIn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eReset_LogIn)
                                    .addComponent(ePetugas))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eAdmin)
                                    .addComponent(eSign_UP)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel8)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNama_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ePassword_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(eMasyarakat)
                    .addComponent(ePetugas)
                    .addComponent(eAdmin))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eSubmit_LogIn)
                    .addComponent(eReset_LogIn)
                    .addComponent(eSign_UP))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eSubmit_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSubmit_LogInActionPerformed
        // TODO add your handling code here:
        
        
        String Status;
        if (eMasyarakat.isSelected()) {
            Status = "Masyarakat";
        } else if (ePetugas.isSelected()) {
            Status = "Petugas";
        } else {
            Status = "Admin";
        }
        
    }//GEN-LAST:event_eSubmit_LogInActionPerformed

    private void eNama_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNama_LogInActionPerformed
        // TODO add your handling code here:
        String nama = eNama_LogIn.getText();
        eNama_LogIn.setText(nama);
    }//GEN-LAST:event_eNama_LogInActionPerformed

    private void ePassword_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePassword_LogInActionPerformed
        // TODO add your handling code here:
        String pw = ePassword_LogIn.getText();
        ePassword_LogIn.setText(pw);
    }//GEN-LAST:event_ePassword_LogInActionPerformed

    private void eReset_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eReset_LogInActionPerformed
        // TODO add your handling code here:
        eNama_LogIn.setText("");
        ePassword_LogIn.setText("");
    }//GEN-LAST:event_eReset_LogInActionPerformed

    private void eSign_UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSign_UPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eSign_UPActionPerformed

    private void ePassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ePassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnStatusLogIn;
    private javax.swing.JRadioButton eAdmin;
    private javax.swing.JRadioButton eMasyarakat;
    private javax.swing.JTextField eNama_LogIn;
    private javax.swing.JPasswordField ePassword1;
    private javax.swing.JPasswordField ePassword_LogIn;
    private javax.swing.JRadioButton ePetugas;
    private javax.swing.JTextArea eReport_LogIn;
    private javax.swing.JButton eReset_LogIn;
    private javax.swing.JButton eSign_UP;
    private javax.swing.JButton eSubmit_LogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
