/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pelaporan;

/**
 *
 * @author RIFAI
 */
public class cMasyarakat extends javax.swing.JFrame {

    /**
     * Creates new form cMasyarakat
     */
    public cMasyarakat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eNim1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnStatusMasyarakat = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        eUserName_Masyarakat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        eTgl_Pengaduan_Masyarakat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        eIsi_Laporan_Masyarakat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        eIsi_Laporan_Masyarakat1 = new javax.swing.JTextField();
        e = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        eReport_Masyarakat = new javax.swing.JTextArea();
        eProses_Masyarakat = new javax.swing.JRadioButton();
        eSelesai_Masyarakat = new javax.swing.JRadioButton();

        eNim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNim1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setText("Lembar Pelaporan Masyarakat");

        eUserName_Masyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eUserName_MasyarakatActionPerformed(evt);
            }
        });

        jLabel13.setText("UserName : ");

        jLabel14.setText("Tanggal Pengaduan : ");

        eTgl_Pengaduan_Masyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTgl_Pengaduan_MasyarakatActionPerformed(evt);
            }
        });

        jLabel15.setText("Isi Laporan : ");

        eIsi_Laporan_Masyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIsi_Laporan_MasyarakatActionPerformed(evt);
            }
        });

        jLabel16.setText("Foto : ");

        eIsi_Laporan_Masyarakat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIsi_Laporan_Masyarakat1ActionPerformed(evt);
            }
        });

        e.setText("Status : ");

        eReport_Masyarakat.setColumns(20);
        eReport_Masyarakat.setRows(5);
        jScrollPane2.setViewportView(eReport_Masyarakat);

        btnStatusMasyarakat.add(eProses_Masyarakat);
        eProses_Masyarakat.setText("Proses");

        btnStatusMasyarakat.add(eSelesai_Masyarakat);
        eSelesai_Masyarakat.setText("Selesai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(e))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eProses_Masyarakat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eSelesai_Masyarakat))
                            .addComponent(eIsi_Laporan_Masyarakat1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eIsi_Laporan_Masyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(eTgl_Pengaduan_Masyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eUserName_Masyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel12)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eUserName_Masyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(eTgl_Pengaduan_Masyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(eIsi_Laporan_Masyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(eIsi_Laporan_Masyarakat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e)
                    .addComponent(eProses_Masyarakat)
                    .addComponent(eSelesai_Masyarakat))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eNim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNim1ActionPerformed

    private void eUserName_MasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eUserName_MasyarakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eUserName_MasyarakatActionPerformed

    private void eTgl_Pengaduan_MasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTgl_Pengaduan_MasyarakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTgl_Pengaduan_MasyarakatActionPerformed

    private void eIsi_Laporan_MasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIsi_Laporan_MasyarakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIsi_Laporan_MasyarakatActionPerformed

    private void eIsi_Laporan_Masyarakat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIsi_Laporan_Masyarakat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIsi_Laporan_Masyarakat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cMasyarakat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnStatusMasyarakat;
    private javax.swing.JLabel e;
    private javax.swing.JTextField eIsi_Laporan_Masyarakat;
    private javax.swing.JTextField eIsi_Laporan_Masyarakat1;
    private javax.swing.JTextField eNim1;
    private javax.swing.JRadioButton eProses_Masyarakat;
    private javax.swing.JTextArea eReport_Masyarakat;
    private javax.swing.JRadioButton eSelesai_Masyarakat;
    private javax.swing.JTextField eTgl_Pengaduan_Masyarakat;
    private javax.swing.JTextField eUserName_Masyarakat;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
