/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pelaporan;

/**
 *
 * @author RIFAI
 */
public class cSignUp extends javax.swing.JFrame {

    /**
     * Creates new form cSignUp
     */
    public cSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        ePassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        eSubmit1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        eReport1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        eNik = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        eNama_SignUp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        eSubmit_SignUp = new javax.swing.JButton();
        eReset_SignUp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eReport_SignUp = new javax.swing.JTextArea();
        eUserName_SignUp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        eNo_Telp_SignUp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ePassword_SignUp = new javax.swing.JPasswordField();

        jLabel8.setText("Log-In Aplikasi Pelaporan Pengaduan Masyarakat");

        eNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNamaActionPerformed(evt);
            }
        });

        ePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePasswordActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama Lengkap : ");

        jLabel10.setText("Password : ");

        eSubmit1.setText("Submit");
        eSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSubmit1ActionPerformed(evt);
            }
        });

        eReport1.setColumns(20);
        eReport1.setRows(5);
        jScrollPane3.setViewportView(eReport1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setText("NIK : ");

        eNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNikActionPerformed(evt);
            }
        });

        jLabel15.setText("Sign-Up Aplikasi Pelaporan Pengaduan Masyarakat");

        jLabel16.setText("Nama : ");

        eNama_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNama_SignUpActionPerformed(evt);
            }
        });

        jLabel17.setText("Password : ");

        eSubmit_SignUp.setText("Submit");
        eSubmit_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSubmit_SignUpActionPerformed(evt);
            }
        });

        eReset_SignUp.setText("Reset");
        eReset_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eReset_SignUpActionPerformed(evt);
            }
        });

        eReport_SignUp.setColumns(20);
        eReport_SignUp.setRows(5);
        jScrollPane1.setViewportView(eReport_SignUp);

        eUserName_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eUserName_SignUpActionPerformed(evt);
            }
        });

        jLabel18.setText("UserName : ");

        eNo_Telp_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNo_Telp_SignUpActionPerformed(evt);
            }
        });

        jLabel19.setText("Telepon : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eUserName_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eNama_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eNik, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eSubmit_SignUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eReset_SignUp))
                            .addComponent(eNo_Telp_SignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ePassword_SignUp))))
                .addGap(0, 323, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel15)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(eNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(eNama_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eUserName_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ePassword_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNo_Telp_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eSubmit_SignUp)
                    .addComponent(eReset_SignUp))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNamaActionPerformed
        // TODO add your handling code here:
        String nama = eNama.getText();
        eNama.setText(nama);
    }//GEN-LAST:event_eNamaActionPerformed

    private void ePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePasswordActionPerformed
        // TODO add your handling code here:
        String pw = ePassword.getText();
        ePassword.setText(pw);
    }//GEN-LAST:event_ePasswordActionPerformed

    private void eNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNikActionPerformed
        // TODO add your handling code here:
        String nim = eNik.getText();
        eNik.setText(nim);
    }//GEN-LAST:event_eNikActionPerformed

    private void eNama_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNama_SignUpActionPerformed
        // TODO add your handling code here:
        String nama = eNama_SignUp.getText();
        eNama_SignUp.setText(nama);
    }//GEN-LAST:event_eNama_SignUpActionPerformed

    private void eSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSubmit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eSubmit1ActionPerformed

    private void eSubmit_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSubmit_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eSubmit_SignUpActionPerformed

    private void eReset_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eReset_SignUpActionPerformed
        // TODO add your handling code here:
        eNik.setText("");
        eNama_SignUp.setText("");
        ePassword_SignUp.setText("");
        eUserName_SignUp.setText("");
        eNo_Telp_SignUp.setText("");
    }//GEN-LAST:event_eReset_SignUpActionPerformed

    private void eUserName_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eUserName_SignUpActionPerformed
        // TODO add your handling code here:
        String user = eUserName_SignUp.getText();
        eUserName_SignUp.setText(user);
    }//GEN-LAST:event_eUserName_SignUpActionPerformed

    private void eNo_Telp_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNo_Telp_SignUpActionPerformed
        // TODO add your handling code here:
        String telp = eNo_Telp_SignUp.getText();
        eNo_Telp_SignUp.setText(telp);
    }//GEN-LAST:event_eNo_Telp_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eNama_SignUp;
    private javax.swing.JTextField eNik;
    private javax.swing.JTextField eNo_Telp_SignUp;
    private javax.swing.JPasswordField ePassword;
    private javax.swing.JPasswordField ePassword_SignUp;
    private javax.swing.JTextArea eReport1;
    private javax.swing.JTextArea eReport_SignUp;
    private javax.swing.JButton eReset_SignUp;
    private javax.swing.JButton eSubmit1;
    private javax.swing.JButton eSubmit_SignUp;
    private javax.swing.JTextField eUserName_SignUp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
